#!/bin/sh
# Runs chromium with some default flags suitable for automation.
# Flags taken from: https://github.com/westy92/headless-chrome-alpine/blob/master/Dockerfile

/usr/lib/chromium/chrome-bin \
    --headless \
    --no-sandbox \
    --disable-background-networking \
    --disable-default-apps \
    --disable-popup-blocking \
    --disable-extensions \
    --disable-gpu \
    --disable-sync \
    --incognito \
    --disable-blink-features=AutomationControlled \
    --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
    --disable-translate \
    --hide-scrollbars \
    --metrics-recording-only \
    --mute-audio \
    --no-first-run \
    --safebrowsing-disable-auto-update \
    "$@"
